services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          memory: 600M
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d/nginx.conf.tpl:/etc/nginx/conf.d/nginx.conf.tpl:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    environment:
      - domain=${domain}
    command: >
      sh -c "
        envsubst '\${domain}' < /etc/nginx/conf.d/nginx.conf.tpl > /etc/nginx/conf.d/nginx.conf &&
        if [ ! -f /etc/letsencrypt/live/\${domain}/fullchain.pem ]; then
          sed -i '/# START_SSL/,/# END_SSL/d' /etc/nginx/conf.d/nginx.conf;
          last_mtime=0;
        else
          last_mtime=\$(stat -c %Y /etc/letsencrypt/live/\${domain}/fullchain.pem);
        fi &&
        nginx &&
        while true; do
          if [ -f /etc/letsencrypt/live/\${domain}/fullchain.pem ]; then
            current_mtime=\$(stat -c %Y /etc/letsencrypt/live/\${domain}/fullchain.pem);
            if [ \$current_mtime -ne \$last_mtime ]; then
              envsubst '\${domain}' < /etc/nginx/conf.d/nginx.conf.tpl > /etc/nginx/conf.d/nginx.conf;
              nginx -s reload;
              last_mtime=\$current_mtime;
            fi;
          else
            last_mtime=0;
          fi;
          sleep 30;
        done
      "
    restart: unless-stopped

  certbot:
    image: certbot/certbot:v5.1.0
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: |
      sh -c '
        if [ ! -f /etc/letsencrypt/live/${domain}/fullchain.pem ]; then
          certbot certonly --webroot -w /var/www/certbot -d ${domain} --agree-tos -m ${email} --non-interactive
        fi
        while true; do
          certbot renew --webroot -w /var/www/certbot --quiet
          sleep 86400
        done
      '
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://nginx:8080/metrics
    depends_on:
      - nginx
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    ports:
      - "9115:9115"
    depends_on:
      - nginx
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.8.2
    ports:
      - 9100:9100
    volumes:
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.13.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml.tpl:/etc/prometheus/prometheus.yml.tpl:ro
      - ./prometheus/data:/prometheus/data
    environment:
      - domain=${domain}
    entrypoint: /bin/sh
    command: -c "sed 's/\\$${domain}/'$$domain'/g' /etc/prometheus/prometheus.yml.tpl > /etc/prometheus/prometheus.yml && /bin/prometheus --config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.1.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${login}
      - GF_SECURITY_ADMIN_PASSWORD=${password}
    volumes:
      - ./grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./grafana/data:/var/lib/grafana
    restart: unless-stopped

  # loki:
  #   image: grafana/loki:3.7.3
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - ./loki/data:/loki
  #     - ./loki/loki.yml:/etc/loki/loki.yml:ro
  #   restart: unless-stopped

  # promtail:
  #   image: grafana/promtail:3.6.11
  #   volumes:
  #     - ./nginx/logs:/var/log/nginx:ro
  #     - ./promtail/promtail.yml:/etc/promtail/promtail.yml:ro
  #     - /var/log:/var/log/host:ro
  #   command: -config.file=/etc/promtail/promtail.yml
  #   restart: unless-stopped
  #   depends_on:
  #     - loki