services:

  nginx:
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - URL=${domain}
      - VALIDATION=http
      - TZ=Europe/Moscow
    volumes:
      - ./nginx/html:/config/www
      - ./nginx/conf.d/default.conf:/config/nginx/site-confs/default.conf:ro
      - ./swag/config:/config
    restart: unless-stopped
    #

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://swag:8080/metrics
    depends_on:
      - nginx
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    ports:
      - "9115:9115"
    depends_on:
      - nginx
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.8.2
    ports:
      - 9100:9100
    volumes:
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.13.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml.tpl:/etc/prometheus/prometheus.yml.tpl:ro
      - ./prometheus/data:/prometheus/data
    environment:
      - domain=${domain}
    entrypoint: /bin/sh
    command: -c "sed 's/\\$${domain}/'$$domain'/g' /etc/prometheus/prometheus.yml.tpl > /etc/prometheus/prometheus.yml && /bin/prometheus --config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.1.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${login}
      - GF_SECURITY_ADMIN_PASSWORD=${password}
    volumes:
      - ./grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./grafana/data:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:3.7.3
    ports:
      - "3100:3100"
    volumes:
      - ./loki/data:/loki
      - ./loki/loki.yml:/etc/loki/loki.yml:ro
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.6.11
    volumes:
      - ./nginx/logs:/var/log/nginx:ro
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/log:/var/log/host:ro
    command: -config.file=/etc/promtail/promtail.yml
    restart: unless-stopped
    depends_on:
      - loki